// for all the includes
// include(".//index.html")
include("color guesser/index.html")
include("fake word generator/index.html")
include("graphing calculator/index.html")
include("inverse kinematics/forward/index.html")
include("inverse kinematics/inverse/index.html")
include("particle system/index.html", true)
include("review website/index.html")
include("sprite system/index.html", true)
include("trails/index.html", true)
include("triangle thing/index.html", true)
include("triangle thing 2 electric boogaloo/index.html", true)
include("VTUBER2", true)

getProjectDetails()