// get("color guesser/index.html")
// get("fake word generator/index.html")
// get("graphing calculator/index.html")
// get("inverse kinematics/forward/index.html")
// get("inverse kinematics/inverse/index.html")
// get("particle system/index.html", true)
// get("review website/index.html")
// get("sprite system/index.html", true)
// get("trails/index.html", true)
// get("triangle thing/index.html", true)
// get("triangle thing 2 electric boogaloo/index.html", true)
// get("VTUBER2", true)

addProject("color guesser/index.html", "Color Guesser", "Get a random color and try to guess its rgb value. I made this on a plane so its not that amazing.")
addProject("cyoobcast background/index.html", "CyoobCast background", "A cool little graphic for something I was doing on Youtube.")
addProject("fake word generator/index.html", "Word Generator", "Generates 1000 random combinations of letters which imitate real english words. Pretty useful if you want to make a unique name or language.")
addProject("graphing calculator/index.html", "Graphing Calculator", "A *very* simple graphing calculator which I made pretty quickly. Cool, even though it's painful to use.")
addProject("inverse kinematics/forward/index.html", "Forward Kinematics", "I followed the Coding Train's forward kinematics tutorial. That's about it.")
addProject("inverse kinematics/inverse/index.html", "Inverse Kinematics", "I followed the Coding Train's inverse kinematics tutorial. Kinda looks like a rope.")
addProject("light simulation/index.html", "Light Simulation", "A shader that mimics light in a scene. I might want to go back on it some day.")
addProject("particle system/index.html", "Particle System", "A generic particle system that I can use in other projects. Very satisfying.")
addProject("RAYCASTING GAME/versions/4-current/index.html", "Raycasting game", "A very unfinished 3d-looking game using raycasting. Originally a copy from the Coding Train's video but I added a bunch (color, entities, textures, etc.)")
addProject("SHADERS/3d glasses/index.html", "3D Effect Shader", "A shader that makes a 3d image that you can see by crossing your eyes until the two match up. Takes in a regular image and a depth map. If the depth map isn't smooth and the color image is too simple it creates annoying visible artifacts :(.")
addProject("SHADERS/basic gradient/index.html", "Basic Gradient", "Pretty much the simplest thing you can do with a shader.")
addProject("SHADERS/blur/index.html", "Blur Shader", "Making a custom weighted box blur shader. The function for the weights is unique to me from what I know of. The function itself makes it so that I have to do so many more calculations than I should. Lesson learned.")
addProject("SHADERS/edge detect/index.html", "Edge Detect", "A simple edge detect shader using the camera.")
addProject("SHADERS/infinite pattern/index.html", "Infinite Tile Pattern", "A shader that tiles a smaller image, making 240 particles look like 100,000. Another shader on top giving the color.")
addProject("SHADERS/motion detection shader/index.html", "Camera Motion Detection", " shader that detects motion in your camera.")
addProject("SHADERS/mouse gradient/index.html", "Mouse Gradient", "A shader that applies a gradient to the canvas and then changes it depending on the position of the mouse.")
addProject("SHADERS/webcam rgb shift/index.html", "Camera RGB Shift", "A shader that shifts the red and blue values of your camera, giving a cool glitchy effect.")
addProject("SHADERS/wind wave/index.html", "Wind Wave", "A shader effect that looks like something waving in the wind.")
addProject("smooth noise/index.html", "Smooth Noise", "My attempt at making a perlin-like noise.")
addProject("sprite system/index.html", "Sprite System", "A generic sprite system to use in other projects. I forgot that I haven't finished it. Oops.")
addProject("TETRIS/index.html", "Tetris", "A terrible, unfinished Tetris clone.")
addProject("trails/index.html", "Trails", "The most satisfying thing I've ever made, even though I did it in a little more that 2 hours.")
addProject("triangle thing/index.html", "Triangle Thing", "I tried to get some effect, but it's not exactly what I wanted.")
addProject("triangle thing 2 electric boogaloo/index.html", "Triangle Thing 2: Electric Boogaloo", "Still not what I wanted, but very very cool and very close.")
addProject("triangle thing 3 epic boogalee/index.html", "Triangle Thing 3: The Good One", "Triangulation using the Bowyer-Watson algorithm")
addProject("vtuber2/index.html", "VTuber", "A little VTuber model which uses AI and uses image files.")

// addProject("/index.html", "", "")

// get old glitch projects in there